client_id = "c7549ec466b102db9328dce2a31ec55b"
application_url = "https://example.com"
embedded = true
name = "EcoTraceIT"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
scopes = "read_orders,write_orders,read_products,write_products,write_app_data"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://example.com/auth/callback"]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = ["orders/create", "orders/updated"]
  uri = "/webhooks/orders"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"
